language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'

install:
    - composer install --no-interaction

cache:
    directories:
        - vendor

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon --level=max --no-interaction --no-progress src/ tests/
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
